prettier
prettier

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,181 +2,181 @@ name: Build & Test
 "on":
   push:
     branches:
-    - '*'
+      - "*"
   pull_request:
     branches:
-    - '*'
+      - "*"
   schedule:
-  - cron: 01 13 * * SAT
+    - cron: 01 13 * * SAT
 jobs:
   stage1:
     name: Stage 1
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
-      with:
-        go-version: '>=1.21'
-    - name: Build
-      run: go build -v
-    - name: Run Stage
-      run: ./britishinput fail
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
+        with:
+          go-version: ">=1.21"
+      - name: Build
+        run: go build -v
+      - name: Run Stage
+        run: ./britishinput fail
   stage2:
     needs: stage1
     if: failure()
     name: Stage 2
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
-      with:
-        go-version: '>=1.21'
-    - name: Build
-      run: go build -v
-    - name: Run Stage
-      run: ./britishinput fail
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
+        with:
+          go-version: ">=1.21"
+      - name: Build
+        run: go build -v
+      - name: Run Stage
+        run: ./britishinput fail
   stage3:
     needs: stage2
     if: failure()
     name: Stage 3
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
-      with:
-        go-version: '>=1.21'
-    - name: Build
-      run: go build -v
-    - name: Run Stage
-      run: ./britishinput fail
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
+        with:
+          go-version: ">=1.21"
+      - name: Build
+        run: go build -v
+      - name: Run Stage
+        run: ./britishinput fail
   stage4:
     needs: stage3
     if: failure()
     name: Stage 4
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
-      with:
-        go-version: '>=1.21'
-    - name: Build
-      run: go build -v
-    - name: Run Stage
-      run: ./britishinput fail
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
+        with:
+          go-version: ">=1.21"
+      - name: Build
+        run: go build -v
+      - name: Run Stage
+        run: ./britishinput fail
   stage5:
     needs: stage4
     if: failure()
     name: Stage 5
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
-      with:
-        go-version: '>=1.21'
-    - name: Build
-      run: go build -v
-    - name: Run Stage
-      run: ./britishinput pass
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
+        with:
+          go-version: ">=1.21"
+      - name: Build
+        run: go build -v
+      - name: Run Stage
+        run: ./britishinput pass
   stage6:
     needs: stage5
     if: failure()
     name: Stage 6
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
-      with:
-        go-version: '>=1.21'
-    - name: Build
-      run: go build -v
-    - name: Run Stage
-      run: ./britishinput
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
+        with:
+          go-version: ">=1.21"
+      - name: Build
+        run: go build -v
+      - name: Run Stage
+        run: ./britishinput
   stage7:
     needs: stage6
     if: failure()
     name: Stage 7
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
-      with:
-        go-version: '>=1.21'
-    - name: Build
-      run: go build -v
-    - name: Run Stage
-      run: ./britishinput
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
+        with:
+          go-version: ">=1.21"
+      - name: Build
+        run: go build -v
+      - name: Run Stage
+        run: ./britishinput
   stage8:
     needs: stage8
     if: failure()
     name: Stage 8
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
-      with:
-        go-version: '>=1.21'
-    - name: Build
-      run: go build -v
-    - name: Run Stage
-      run: ./britishinput
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
+        with:
+          go-version: ">=1.21"
+      - name: Build
+        run: go build -v
+      - name: Run Stage
+        run: ./britishinput
   stage9:
     needs: stage8
     if: failure()
     name: Stage 9
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
-      with:
-        go-version: '>=1.21'
-    - name: Build
-      run: go build -v
-    - name: Run Stage
-      run: ./britishinput
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
+        with:
+          go-version: ">=1.21"
+      - name: Build
+        run: go build -v
+      - name: Run Stage
+        run: ./britishinput
   stage10:
     needs: stage9
     if: failure()
     name: Stage 10
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
-      with:
-        go-version: '>=1.21'
-    - name: Build
-      run: go build -v
-    - name: Run Stage
-      run: ./britishinput
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed
+        with:
+          go-version: ">=1.21"
+      - name: Build
+        run: go build -v
+      - name: Run Stage
+        run: ./britishinput
   final-status:
     needs:
-    - stage1
-    - stage2
-    - stage3
-    - stage4
-    - stage5
-    - stage6
-    - stage7
-    - stage8
-    - stage9
-    - stage10
+      - stage1
+      - stage2
+      - stage3
+      - stage4
+      - stage5
+      - stage6
+      - stage7
+      - stage8
+      - stage9
+      - stage10
     if: always()
     runs-on: ubuntu-latest
     steps:
-    - name: Check Final Status
-      run: |-
-        if [[ "${{ needs.stage1.result }}" == "success" ]] || \
-           [[ "${{ needs.stage2.result }}" == "success" ]] || \
-           [[ "${{ needs.stage3.result }}" == "success" ]] || \
-           [[ "${{ needs.stage4.result }}" == "success" ]] || \
-           [[ "${{ needs.stage5.result }}" == "success" ]] || \
-           [[ "${{ needs.stage6.result }}" == "success" ]] || \
-           [[ "${{ needs.stage7.result }}" == "success" ]] || \
-           [[ "${{ needs.stage8.result }}" == "success" ]] || \
-           [[ "${{ needs.stage9.result }}" == "success" ]] || \
-           [[ "${{ needs.stage10.result }}" == "success" ]]; then
-          echo "Pipeline succeeded - a stage passed"
-          exit 0
-        else
-          echo "Pipeline failed - no stage passed"
-          exit 1
-        fi
+      - name: Check Final Status
+        run: |-
+          if [[ "${{ needs.stage1.result }}" == "success" ]] || \
+             [[ "${{ needs.stage2.result }}" == "success" ]] || \
+             [[ "${{ needs.stage3.result }}" == "success" ]] || \
+             [[ "${{ needs.stage4.result }}" == "success" ]] || \
+             [[ "${{ needs.stage5.result }}" == "success" ]] || \
+             [[ "${{ needs.stage6.result }}" == "success" ]] || \
+             [[ "${{ needs.stage7.result }}" == "success" ]] || \
+             [[ "${{ needs.stage8.result }}" == "success" ]] || \
+             [[ "${{ needs.stage9.result }}" == "success" ]] || \
+             [[ "${{ needs.stage10.result }}" == "success" ]]; then
+            echo "Pipeline succeeded - a stage passed"
+            exit 0
+          else
+            echo "Pipeline failed - no stage passed"
+            exit 1
+          fi
