iter

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -42,7 +42,7 @@ jobs:
              [[ "${{ needs.stage2.result }}" == "success" ]]; then \
             echo "Pipeline succeeded - a stage passed"
             exit 0
-          else
-            echo "Pipeline failed - no stage passed"
-            exit 1
           fi
+
+          echo "Pipeline failed - no stage passed"
+          exit 1
